path_classifiers:
  test:
    - exclude: /
    - AeroFoil_UI_Files
    - .travis.yml
    - AeroFoil.zip
    - INSTALL.sh
    - LICENSE
    - README.md
  
extraction:
  python:
    python_setup:
      version: 3
