codecov: true
language: python
before_script:
  - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
  - sudo apt update
  - sudo apt-get install -y freecad
  - sudo apt-get install -y qt5-default
install:
  - pip install codecov
  - pip install coverage
  - pip install pytest
script:
  - if freecad AeroFoil.FCMacro & then echo "True"; kill $!; else echo "False"; fi
after_success:
  - py.test AeroFoil.FCMacro --cov=codecov
  - codecov
