codecov: true
language: python
before_script:
  - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
  - sudo apt update
  - sudo apt-get install -y freecad
  - sudo apt-get install -y qt5-default
script:
  - if freecad AeroFoil.FCMacro & then echo "True"; kill $!; else echo "False"; fi
after_success:
  - pip install coverage
  - bash <(curl -s https://codecov.io/bash)
