language: python
before_script:
  - sudo add-apt-repository ppa:freecad-maintainers/freecad-stable
  - sudo apt update
  - sudo apt install freecad
  - sudo apt-get install qt5-default
script:
  - python AeroFoil.FCMacro
